on: 
  push:
    paths:
      - rust/**
      - docker/rust/**
      - .github/**


name: Clippy check
env:
  RUSTFLAGS: "-Dwarnings" 

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: |
          cd rust
          cargo clippy --all-targets --all-features

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run cargo test
        run: |
          cd rust
          cargo test

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/rust/Dockerfile
          tags: mattfly/hanb:latest,mattfly/hanb:${{ github.sha }}
          push: true
